### ISSUE TITLE
No dist folder on ui.service

### ISSUE THREAD

**Issue by hcs-bernardo-rufino** [PatrickKalkman/leave-deploy#3]
On the ui.service Dockerfile you have:

```dockerfile
FROM nginx:latest
COPY ./dist/ /usr/share/nginx/html/
```

But there is no ./dist folder there.

What am i missing?

**Comment by PatrickKalkman** [comment]
Hi Bernardo,

The dist folder is created when the Angular ui (prediction-ui) is build using "ng build"

**Comment by hcs-bernardo-rufino** [comment]
> 

Thanks for replying, i realized a few minutes after opening the thread... my bad.
